import React from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Tooltip,
  Legend,
  Title,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';
import {
  Card,
  CardContent,
  Typography,
  Box,
} from '@mui/material';

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend, Title);

const UserReportBarGraphWidget = ({ userReports }) => {
  const labels = userReports.map(user => user.name);
  const values = userReports.map(user => user.reportCount);

  const data = {
    labels,
    datasets: [
      {
        label: 'Reports Generated',
        data: values,
        backgroundColor: '#42a5f5',
        borderRadius: 6,
        barThickness: 35,
        barPercentage: 0.6,       // Width of bars relative to category width
        categoryPercentage: 0.7,  // Space between bars (lower = more space)
      },
    ],
  };

  const options = {
    responsive: true,
    plugins: {
      legend: { display: false },
      tooltip: { mode: 'index', intersect: false },
      title: { display: true, text: 'Reports Generated by Users' },
    },
    scales: {
      x: {
        title: { display: true, text: 'Users' },
        grid: { display: false },
      },
      y: {
        beginAtZero: true,
        title: { display: true, text: 'Report Count' },
        ticks: { precision: 0 },
      },
    },
  };

  return (
    <Card elevation={3} sx={{ p: 2 }}>
      <CardContent>
        <Box>
          <Bar data={data} options={options} />
        </Box>
      </CardContent>
    </Card>
  );
};

export default UserReportBarGraphWidget;
